//
//  hiddenSingleton.h
//  hiddenSingleton
//
//  Created by ZHANGPENG on 10/12/14.
//  Copyright (c) 2014 . All rights reserved.
//

// - we may introduce a ARC based singlton object -> object have a core obj and shell obj
// - user alloc and use shell obj whenever they want
// - core obj is a singleton object which can be dismissed by persiste its data into file/db and re-generated by loading its data from file/db
// - whenever there is a shell object exists, core obj shall be loaded and exist by singleton in the memory
// - if all the shell objects is released, core obj shall be dismissed and it's data shall be persistented in the file/db.

#import <Foundation/Foundation.h>

// first we need a singleton class
@interface singletonClass : NSObject

- (id) init;

@end

@interface hiddenSingleton : NSObject

- (id) init;

@end
